/* Read-only share viewer — no login; the API enforces what a link can see. */
/* global html, useState, useEffect, api, Chip, Spinner, EmptyState, BenchmarkCard, BoardPackView, Term */

function ShareApp() {
  const token = window.location.pathname.split("/").pop();
  const [data, setData] = useState(undefined);
  useEffect(() => {
    api(`/api/share/${token}/data`).then(setData).catch(e => setData({ error: e.message }));
  }, [token]);
  if (data === undefined) return html`<div class="auth-wrap"><${Spinner} /></div>`;
  if (data.error) return html`
    <div class="auth-wrap"><div class="card auth-card" style=${{ textAlign: "center" }}>
      <div class="logo" style=${{ padding: 0 }}>lumi<span>.benchmark</span></div>
      <div style=${{ fontSize: "30px", margin: "16px 0 8px" }}>⏳</div>
      <b>This share link is no longer available</b>
      <p class="caption">It may have expired or been revoked by the organisation that created it.</p>
    </div></div>`;
  if (data.kind === "boardpack") {
    return html`
      <div style=${{ padding: "24px 12px" }}>
        <div class="row spread no-print" style=${{ maxWidth: "210mm", margin: "0 auto 16px" }}>
          <span class="caption">Shared read-only by ${data.org_name} · powered by lumi</span>
          <button class="btn primary" onClick=${() => window.print()}>Download PDF</button>
        </div>
        <${BoardPackView} packId=${null} shared=${true} sharedData=${data} />
      </div>`;
  }
  const h = data.headline;
  return html`
    <div style=${{ maxWidth: "1180px", margin: "0 auto", padding: "24px 16px" }}>
      <div class="row spread" style=${{ marginBottom: "16px" }}>
        <div>
          <div class="logo" style=${{ padding: 0 }}>lumi<span>.benchmark</span></div>
          <h1 class="display-title" style=${{ marginTop: "6px" }}>${data.org_name}</h1>
          <div class="caption">Shared read-only benchmark view · peer group: ${data.cut.dim === "all" ? "All peers" : data.cut.value} (${(data.peer_pool || {}).responding_orgs} organisations)</div>
        </div>
        <${Chip} kind="accent">Read-only<//>
      </div>
      <div class="card banner" style=${{ marginBottom: "16px" }}>
        <div>
          <div class="section-title" style=${{ marginBottom: "2px" }}>Above the peer median on ${h.above_median} of ${h.comparable_metrics} comparable metrics</div>
          <div class="caption">${h.below_median} below · ${h.broadly_in_line} broadly in line · figures resting on fewer than 5 organisations are never shown</div>
        </div>
      </div>
      <div class="grid2" style=${{ marginBottom: "16px" }}>
        <div><h2 class="section-title">Where they lead</h2>
          ${data.callouts.strengths.map((t, i) => html`<div key=${i} class="callout good">${t}</div>`)}</div>
        <div><h2 class="section-title">Biggest gaps to peers</h2>
          ${data.callouts.gaps.map((t, i) => html`<div key=${i} class="callout bad">${t}</div>`)}</div>
      </div>
      <div class="bench-grid">
        ${data.cards.map(c => html`<${BenchmarkCard} key=${c.id} card=${c} prefs=${{}} />`)}
      </div>
      <div class="caption" style=${{ margin: "24px 0", textAlign: "center" }}>
        Generated by lumi people analytics benchmarking · percentiles use linear interpolation · n &lt; 5 suppressed throughout
      </div>
    </div>`;
}

ReactDOM.createRoot(document.getElementById("root")).render(html`<${ShareApp} />`);
