#!/usr/bin/env python3
"""Plain-English review of metric DEFINITIONS (the metric-page 'what this means' line) — 2026-08-10.

Reviewed all 333 active definitions (6-slice generate + per-slice accuracy verify vs
question + options). The field was in poor shape: 158 were verbatim copies of the
question, 33 were auto-generated boilerplate ('Binary indicator for whether...'), and
some described a different metric than the question. Replaced 308 with accurate,
one-sentence plain-English definitions that explain what the metric captures and how to
read the answer scale (distinct from the question, no invented facts, British spelling).
Text-only (definition column); options/type/values untouched. DB is the live source the
app serves (library.py -> the metric page 'Question & definition' card). LUMI_DB-aware;
DRY-RUN unless --write --confirmed-by-david.
"""
import os, sys, sqlite3

DB = os.environ.get("LUMI_DB") or os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "lumi.db")
WRITE = "--write" in sys.argv and "--confirmed-by-david" in sys.argv

REWRITES = {
    '323ffcf1-749b-43f3-bf34-1de6b8b1ca67': "The maximum bonus achievable at each job level, expressed as a percentage of base salary.",
    '3faf1f0c-f753-497f-a395-384bba38c5e3': "Average yearly PMI premium the organisation pays per employee, broken down by level of cover.",
    'ALLOW_02': "Whether allowance levels are reviewed on a regular governed cycle rather than only ad hoc.",
    'ALLOW_03': "Whether allowances count towards pensionable pay, and whether this applies to all allowances or only some.",
    'ALLOW_04': "Whether allowance amounts or eligibility vary by role level rather than applying uniformly to all employees.",
    'CAR_BN_02': "The factors that qualify an employee for a company car provided because the role requires one.",
    'CAR_COST_02': "Whether company car policy requires or gives preference to low-emission or electric vehicles.",
    'CAR_STATUS_01': "Whether company cars are given as a perk linked to seniority or grade, not business need.",
    'CAR_STATUS_03': "Whether eligible employees can take a cash allowance instead of a status-based company car.",
    'EXT_REW_GAP_001': "The yearly amount budgeted per employee to fund recognition awards, or none.",
    'EXT_REW_GAP_002': "The typical monetary value of a single individual recognition award, or non-financial only.",
    'EXT_REW_GAP_003': "Whether formal or informal caps limit how often one employee can receive recognition awards.",
    'EXT_REW_GAP_004': "Whether the organisation runs a scheme rewarding employees for reaching length-of-service milestones.",
    'EXT_REW_GAP_005': "The service anniversaries at which the organisation gives a long service award.",
    'EXT_REW_GAP_007': "The typical value of the award given at the organisation's main long-service milestone.",
    'EXT_REW_GAP_009': "How often remote-eligible employees are expected to attend a workplace, from fully remote upwards.",
    'EXT_REW_GAP_010': "The geographic limits on where remote employees may work, from UK-only to international.",
    'EXT_REW_GAP_011': "Which home-working costs the organisation reimburses, such as equipment, connectivity or utilities.",
    'EXT_REW_GAP_012': "How regularly the benefits package is reviewed to check it stays relevant and good value.",
    'EXT_REW_GAP_013': "How frequently employees are paid, such as weekly, fortnightly or monthly.",
    'OT_03_1a68c68a': "Whether employees can take equivalent time off instead of being paid for overtime worked.",
    'OT_04_b14623a6': "Whether an enhanced rate is paid for working unsocial hours such as nights or weekends.",
    'PAYTR_01_42eae7ec': "Whether the organisation routinely states pay or a pay range in its job adverts.",
    'PAYTR_02_131bd412': "Whether current employees can see the pay band or salary range for their role.",
    'PAYTR_03_db0108d6': "Whether a documented policy sets out how pay progresses within a salary band.",
    'PROP_10d1211d': "Whether the organisation measures pay gaps by disability status at least yearly; 'partially' signals partial coverage.",
    'PROP_11a83d52': "Whether benefits or health plans explicitly provide trans-inclusive support, where legally permitted; partial coverage is a middle option.",
    'PROP_202fecc6': "Whether the organisation monitors take-up and usage of key benefits, and across how many of them.",
    'PROP_216f7323': "Which reward components the strategy formally covers, from base and variable pay to wellbeing and recognition; select all.",
    'PROP_34ffb6e2': "Captures the level at which promotion decisions are controlled, from central criteria-based governance through to manager discretion or ad hoc case-by-case calls.",
    'PROP_930043cc': "Whether the organisation measures its ethnicity pay gap at least yearly; 'partially' signals partial or inconsistent coverage.",
    'PROP_aa4061d5': "The methods used to gauge whether reward and benefits communications land, from open rates to surveys and query volumes.",
    'PROP_c1a3da61': "Whether the organisation helps cover relocation costs for hires who must move for the role, via policy or case by case.",
    'PROP_d992b2ea': "Captures whether a minimum tenure in role or grade is required before promotion, and whether that rule is standard or varies by job family.",
    'PROP_e1d1e604': "Measures the share of employees given a pay rise outside the annual review cycle, excluding promotions; the answer is a banded percentage.",
    'PROP_ef4ff31e': "Captures whether the organisation analyses promotion rates across protected characteristics to detect equity gaps; the answer reflects how regularly this is done.",
    'RED_COST_01': "Average total cost of one redundancy over the last completed year, shown as a pay multiple.",
    'RED_NOTICE_01': "How notice is usually handled in redundancies — worked, garden leave, paid in lieu, or mixed.",
    'RED_PAY_01': "Which pay elements are included when calculating redundancy payments, from basic salary to variable pay.",
    'RED_PROC_01': "Whether a written redundancy process exists and is applied consistently across the organisation.",
    'RED_PROC_02': "Whether the criteria for selecting employees for redundancy are documented and objective.",
    'RED_PROC_03': "Whether redundancy selection outcomes are checked for fairness and potential bias.",
    'RED_PROC_04': "Whether outplacement or career-transition support is offered to employees leaving through redundancy.",
    'RED_PROC_05': "Whether line managers are trained to handle redundancy conversations with affected employees.",
    'RED_TERM_01': "Whether redundancy pay is statutory only or enhanced, and how any enhancement is structured.",
    'RED_TERM_02': "The largest redundancy payment offered, as a multiple of weekly pay and excluding notice.",
    'RED_TERM_03': "The maximum number of weeks' pay used when calculating a redundancy payment.",
    'REW262_GOV_ACTIONPLAN': "Whether a published equality action plan exists and which protected areas it addresses: gender, ethnicity, disability or menopause.",
    'REW262_GOV_AIINPAY': "Whether AI tools inform pay decisions and the governance around them, from no use to human oversight with bias auditing.",
    'REW262_GOV_EQUALPAYAUDIT': "Whether the organisation proactively audits pay for equal-pay risk, and how frequently, from never to more than annually.",
    'REW262_GOV_EQUALVALUE': "How far the organisation can group roles into equal-value categories (skills, effort, responsibility, conditions) for equal-pay comparison, from not at all to fully.",
    'REW262_GOV_PAYINADVERTS': "Whether job adverts state pay or a pay range, and whether this applies to no roles, some roles, or all.",
    'REW262_GOV_SALHISTORY': "Whether the organisation has stopped asking candidates about previous salary during recruitment, a practice linked to reducing pay inequity.",
    'REW262_PAY_AISKILLSPAY': "Whether the organisation pays an additional premium to attract or retain employees with AI skills.",
    'REW262_PAY_CANCELLEDSHIFT': "Whether workers receive compensation when a scheduled shift is cancelled at short notice; not applicable where no shift work exists.",
    'REW262_PAY_GUARANTEEDHRS': "Whether variable-hours workers are offered guaranteed-hours contracts, and whether this is proactive after a reference period, on request only, or not at all.",
    'REW262_PAY_SHIFTNOTICE': "The typical advance notice given to workers before a shift, from no set notice to two or more weeks.",
    'REW262_TIME_BEREAVEMENT': "Whether paid bereavement leave exceeds the statutory minimum, and by how much, from statutory only up to five or more enhanced days.",
    'REW262_TIME_SICKDAYONE': "Whether occupational sick pay (OSP) begins on the first day of absence, with no unpaid waiting days before it starts.",
    'REW263_BEN_CICOVER': "The level of critical illness cover provided, whether none, a fixed lump sum, or a multiple of salary.",
    'REW263_BEN_DENTAL': "Whether dental cover is offered and, if so, whether the employer pays for it or employees fund it voluntarily.",
    'REW263_BEN_NEURO': "How far the organisation supports neurodiverse employees and reasonable adjustments in accessing reward and benefits, from none to a formal process with dedicated support.",
    'REW263_BEN_PENBASIS': "The earnings definition used to calculate pension contributions (banded qualifying earnings, basic pay, or total pay), which affects contribution value.",
    'REW263_BEN_PMIEXCESS': "The cost employees bear on private medical insurance, from no excess to a per-claim or annual excess, or contributing to the premium.",
    'REW263_GOV_BENOBJ': "Whether employee benefits are tied to defined objectives such as retention or engagement, and whether their performance is reviewed against those aims.",
    'REW263_GOV_ETHDISREADY': "Readiness for mandatory ethnicity and disability pay-gap reporting under the Equality (Race and Disability) Bill for employers with 250+ staff.",
    'REW263_GOV_FIREREHIRE': "The organisation's policy for avoiding dismiss-and-rehire when changing pay, pension or benefit terms, from none to a documented policy with a consultation route.",
    'REW263_GOV_FLEXALLOW': "Whether employees receive a flexible benefits allowance they can allocate to their own choices, from none through limited choice to a full personalised allowance.",
    'REW263_GOV_MENOPLAN': "Whether the organisation has, or intends to, publish a voluntary menopause action plan before the 2027 mandate, and how advanced those plans are.",
    'REW263_GOV_REWTEAM': "The size of the organisation's dedicated reward function, from no resource or a shared HR/reward role up to five or more FTE.",
    'REW263_GOV_SIGNOFF': "Which role or body holds final approval of the annual pay and reward decision, such as the HRD, CFO, CEO or Remuneration Committee.",
    'REW263_GOV_UKPAYTRANS': "The organisation's overall pay-transparency maturity, from none through internal ranges and advert ranges to a published transparency policy.",
    'REW263_GOV_UMBRELLA': "Whether reward parity and compliance checks are applied to umbrella-company and agency workers, from none to a full parity framework.",
    'REW263_INC_DEFERRAL': "For bonuses that are deferred, the usual deferral length and form, from one-year cash through multi-year cash to shares or equity.",
    'REW263_INC_POOLFUND': "How the main bonus pool is generated: top-down from profit share, bottom-up from targets, or a hybrid of both.",
    'REW263_PAY_COMPARATIO': "The target pay position within the salary range for fully competent performers, expressed as a compa-ratio relative to the range midpoint.",
    'REW263_PAY_GUARHRSAVG': "Whether zero-/low-hours workers are offered guaranteed-hours contracts based on their average hours, as introduced by the ERA 2025 right to guaranteed hours.",
    'REW263_PAY_MERITMATRIX': "Whether pay increases are differentiated using a merit matrix that combines performance rating with position in the salary range.",
    'REW263_PAY_SHIFTRIGHTS': "Whether zero-/low-hours workers receive reasonable shift notice and short-notice cancellation pay under the ERA 2025 right, covering neither, one, or both.",
    'REW263_PAY_SSPALIGN': "How far sick pay arrangements have been aligned to the April 2026 SSP reform (no lower earnings limit or waiting days), up to enhanced OSP.",
    'REW263_REC_CURRENCY': "The main form recognition awards take: cash, experiences or vouchers, points, or a mix of these.",
    'REW263_REC_IMPACT': "Whether the organisation tracks how its recognition activity affects engagement or retention outcomes.",
    'REW263_REC_MGRBUDGET': "Whether managers control a devolved recognition budget, hold only a central budget, or have none to spend.",
    'REW263_REC_PEER': "Whether employees can recognise each other, from no scheme through informal peer recognition to a points or social-recognition platform.",
    'REW263_TIME_CARERPAID': "Captures whether carer's leave is enhanced with pay above the statutory unpaid entitlement, from none to fully paid.",
    'REW263_TIME_DAYONELEAVE': "Indicates whether paternity and unpaid parental leave are already offered from day one, as required from April 2026.",
    'REW263_TIME_FERTLEAVE': "Indicates whether time off for fertility treatment is dedicated paid leave, rather than drawn from sick or annual leave.",
    'REW263_TIME_HOLRECORDS': "Indicates whether annual-leave and holiday-pay records are kept in line with the six-year retention rule taking effect April 2026.",
    'REW263_TIME_IVF': "Captures the depth of employer-funded fertility treatment, measured as the number of IVF cycles or the financial cap offered.",
    'REW263_TIME_NEONATAL': "Captures whether neonatal care leave is enhanced above the statutory entitlement, through better pay, additional leave, or both.",
    'REW263_TIME_PATPAY': "Captures whether paternity pay is enhanced above statutory and for how many weeks, from none to six-plus.",
    'REW263_TIME_PREGLOSS': "Indicates whether paid leave for pregnancy loss or miscarriage is offered as formal policy, at discretion, or not at all.",
    'REW263_WEL_DATA': "Which wellbeing and health metrics the organisation actively monitors, such as absence rates, PMI claims, wellbeing scores or EAP utilisation; select all that apply.",
    'REW263_WEL_FINWELL': "Indicates whether financial wellbeing is supported by a documented strategy rather than one-off or ad hoc measures.",
    'REW263_WEL_MGRTRAIN': "Measures the share of people managers who have completed mental-health awareness training, banded from none to over three-quarters.",
    'REW263_WEL_OH': "Captures whether an occupational health service exists and how quickly referrals are turned around, from no provision to a guaranteed sub-two-week SLA.",
    'REW264_BEN_EVSALSAC': "Captures whether a salary sacrifice car scheme is restricted to EVs, prioritises them, or is fuel-neutral.",
    'REW264_GOV_AIPAYREVIEW': "Captures whether an employee's AI proficiency factors into base pay review decisions — formally, informally, not at all, or planned.",
    'REW264_GOV_PAYEXPLAIN': "Indicates whether employees can obtain an explanation of how their individual pay was set, through a formal or informal route.",
    'REW264_HLT_BEREAVESUPPORT': "Captures which bereavement support services beyond leave are provided; select all that apply, from counselling to probate help.",
    'REW264_HLT_CANCERPATH': "Captures whether private cancer diagnostics or fast-track pathways are funded as a dedicated benefit, via PMI, or not at all.",
    'REW264_HLT_CASHPLAN': "Captures whether a health cash plan is offered and how it is funded — employer-paid for all, some, voluntary, or none.",
    'REW264_HLT_FERTROUTE': "Captures the delivery route for funded fertility support — a specialist provider, direct reimbursement, or through PMI.",
    'REW264_HLT_GENDERAFF': "Indicates whether gender-affirming healthcare is explicitly supported, covered only under standard PMI terms, or not offered.",
    'REW264_HLT_GIPREHAB': "Captures how actively the rehabilitation and early-intervention services embedded in group income protection are used, if at all.",
    'REW264_HLT_MENSHEALTH': "Indicates whether targeted men's health support — such as screening or prostate/testicular pathways — is provided.",
    'REW264_HLT_OPTICAL': "Indicates whether optical cover or eye-care vouchers extend beyond the statutory DSE eye-test requirement.",
    'REW264_HLT_RISKFLEXUP': "Indicates whether employees can increase group life and/or income protection cover at their own expense.",
    'REW264_HLT_SECONDOPINION': "Indicates whether employees can access a service providing an expert second medical opinion on a diagnosis or treatment.",
    'REW264_HLT_SPOUSELIFE': "Indicates whether life cover for a spouse or partner is offered — employer-paid, on a voluntary basis, or not at all.",
    'REW264_HLT_VIRTUALGP': "Indicates whether a virtual GP service is offered in its own right rather than only bundled within PMI.",
    'REW264_HLT_WOMENSHEALTH': "Captures whether women's health support beyond menopause leave is offered as a clinical benefit, awareness only, or not at all.",
    'REW264_INC_EMICSOP': "Captures which discretionary tax-advantaged share option plans are operated — EMI, CSOP, both, or neither.",
    'REW264_INC_SHAREPLAN': "Captures which all-employee tax-advantaged share plans are operated — SAYE (Sharesave), SIP, both, or neither.",
    'REW264_PAY_HOLPAYMETHOD': "Captures which method calculates holiday pay for irregular-hours and part-year workers, from rolled-up to 52-week averaging.",
    'REW264_PAY_STARTPOLICY': "Captures where new hires are typically placed within the pay range, from below the midpoint to anywhere in range.",
    'REW264_PEN_AEDEFAULT': "Captures the default employee pension contribution for auto-enrolled joiners, measured as percentage points above the statutory minimum.",
    'REW264_PEN_AUTOESC': "Indicates whether pension contributions automatically step up over time, either by default or as an opt-in feature.",
    'REW264_PEN_CONTRIBFLEX': "Indicates whether employees can temporarily lower pension contributions during financial pressure and easily restore them, formally or informally.",
    'REW264_PEN_GREENDEFAULT': "Captures whether the default pension fund carries a published ESG or net-zero commitment, from net-zero aligned to standard.",
    'REW264_PEN_HELPTOSAVE': "Indicates whether the government's Help to Save scheme is actively promoted, merely signposted, or not offered to eligible lower-paid employees.",
    'REW264_PEN_MIDLIFEMOT': "Indicates whether mid-career retirement-planning support (a 'mid-life MOT') is offered as a structured programme, signposting, or not at all.",
    'REW264_PEN_NICSHARING': "Indicates whether employer NIC savings from salary sacrifice are passed back to employees — wholly, partly, or not at all.",
    'REW264_PEN_PAYROLLGIVING': "Indicates whether tax-efficient payroll giving to charity is offered, and whether the employer matches employee donations.",
    'REW264_PEN_PAYROLLLOANS': "Captures whether short-term financial help is available through payroll-deducted loans, an internal hardship fund, both, or neither.",
    'REW264_PEN_SALSACIMPACT': "Captures how far the organisation has assessed the cost impact of the 2029 £2,000 NIC cap on pension salary sacrifice.",
    'REW264_PEN_SALSACRESPONSE': "Captures the organisation's planned response to the 2029 NIC cap on pension salary sacrifice, from unchanged to withdrawal.",
    'REW264_PEN_SIDECAR': "Captures which workplace savings vehicles sit alongside the pension; select all that apply, from ISAs to sidecar savings.",
    'REW264_TIME_CHILDCARE': "Captures which forms of childcare support are provided, from workplace nurseries to backup care; select all that apply.",
    'REW264_TIME_FOURDAY': "Captures whether any group works a four-day week or nine-day fortnight, including at trial stage.",
    'REW264_WEL_COLACTION': "Captures which discrete cost-of-living measures were taken in the past two years; select all that apply.",
    'REW264_WEL_DEBTADVICE': "Indicates whether independent debt or money-guidance support is funded, signposted (e.g. via MaPS), or not provided.",
    'REW264_WEL_EWA': "Captures whether employees can draw earned pay before payday (earned wage access) — across all staff, frontline only, or in pilot.",
    'REW264_WEL_EWACAP': "Indicates whether earned wage access withdrawals are capped, typically as a percentage of pay already accrued.",
    'REW264_WEL_EWAFEES': "Captures who bears the cost of earned wage access transactions — the employer, the employee per use, or a subscription.",
    'REW264_WEL_FINCOACH': "Captures whether personal financial coaching or advice beyond pensions is offered, from funded one-to-one advice to workshops only.",
    'REW264_WEL_MEALS': "Indicates whether staff meals are provided free of charge, at a subsidy, or not at all.",
    'REW264_WEL_RLWACCRED': "Captures the organisation's status against the real Living Wage, from formally accredited to paying it without accreditation.",
    'REW264_WEL_SEASONTICKET': "Indicates whether loans for season tickets or other commuting costs are made available to employees.",
    'REW265_BEN_ENHANCEDVR': "Whether voluntary redundancy packages are more generous than the organisation's compulsory redundancy terms, or matched to them.",
    'REW265_BEN_EVCHARGE': "Whether the workplace offers electric-vehicle charging for employees, free of charge, at a cost, or not at all.",
    'REW265_BEN_GREENBEN': "Which benefits actively support sustainable choices, such as a green pension option, home-energy support, or sustainable-travel incentives.",
    'REW265_BEN_PENBRIDGE': "Whether restructuring includes support for early retirement or bridging pension income until a pension starts, routinely or case-by-case.",
    'REW265_BEN_PMICOMP': "Which enhancements the organisation's private medical insurance includes beyond core cover, such as out-patient, mental health, physiotherapy or dental.",
    'REW265_BEN_TRANSPORT': "Whether the organisation financially supports employee public-transport costs beyond providing season-ticket loans.",
    'REW265_GOV_AIBENCH': "Captures how far AI tools are used in reward benchmarking or market analysis, from embedded in process to exploring.",
    'REW265_GOV_AIDISCLOSE': "Whether the organisation tells employees when AI has informed pay decisions affecting them, ranging from always disclosed to no disclosure.",
    'REW265_GOV_AIREGRADE': "Whether AI's reshaping of job content has triggered any role re-grading or re-evaluation in the past year; higher options indicate broader impact.",
    'REW265_GOV_AITALENT': "Indicates whether AI or digital talent gets differentiated reward — separate ranges, RSUs or retention vehicles — formally or case-by-case.",
    'REW265_GOV_BROKER': "Whether the organisation engages an external benefits broker or adviser, on a full-service basis, for projects, or not at all.",
    'REW265_GOV_COMPSOFT': "What technology supports pay review cycles, from dedicated compensation software or an HRIS module to outsourcing or spreadsheets.",
    'REW265_GOV_EIA': "Whether reward changes undergo an equality impact assessment before launch, always, only for major changes, or never.",
    'REW265_GOV_GPGNAMING': "Whether the organisation is ready to name outsourced-worker providers in its gender pay gap report, as the Employment Rights Act will require.",
    'REW265_GOV_PAYAPPEAL': "Whether employees can formally challenge their pay review outcome, via a dedicated appeal route, the grievance process, or not at all.",
    'REW265_GOV_REBROKE': "How often the organisation runs a full market review or re-broke of its benefits, from annually to never.",
    'REW265_GOV_SOCIOECON': "Whether the organisation analyses pay outcomes by employees' socio-economic background, already doing so, considering it, or not.",
    'REW265_GOV_TAKEUP': "Whether the organisation tracks how much benefits are used and feeds that into design decisions, systematically, occasionally, or not.",
    'REW265_GOV_TRS': "The share of employees who receive a total reward statement, from all staff through some populations to none.",
    'REW265_GOV_VOLGAPS': "Which pay gaps the organisation discloses voluntarily beyond mandatory gender reporting, such as ethnicity, disability, or CEO pay ratio.",
    'REW265_INC_BONUSDISC': "How far judgement can override a bonus formula's result, from no discretion through documented committee discretion to undocumented adjustment.",
    'REW265_INC_BONUSTIME': "How soon after the performance year ends annual bonuses reach employees, banded by months elapsed.",
    'REW265_INC_BUYOUT': "Whether the organisation compensates senior recruits for bonuses forfeited on leaving a previous employer, and how often.",
    'REW265_INC_COMMCAP': "Whether sales commission earnings are limited, distinguishing uncapped plans from soft caps or decelerators and firm hard caps.",
    'REW265_INC_EOT': "Whether an employee-ownership model such as an Employee Ownership Trust is established, being considered, or absent.",
    'REW265_INC_ESGINCENT': "Whether incentive plans embed non-financial measures like ESG, safety or people goals, either as weighted metrics or as a modifier/underpin.",
    'REW265_INC_PROFITSHARE': "Whether staff broadly share in company profits or team gains, distinguishing all-employee profit share from site or team gainshare.",
    'REW265_INC_RETENTION': "Whether bonuses are used to retain or reward completion by employees in critical roles, and whether this is formalised.",
    'REW265_INC_SAYEDISC': "The discount applied to the share option price under a Save As You Earn scheme, where 20% is the statutory maximum.",
    'REW265_INC_SHAREPART': "The share of eligible employees actively participating in the all-employee share plan, banded from under 10% to over half.",
    'REW265_INC_SIPELEM': "Which components of a Share Incentive Plan the organisation uses — free, partnership, matching or dividend shares — or none.",
    'REW265_PAY_ACTINGUP': "Whether pay for temporarily covering a higher role or a secondment follows a documented allowance policy or is decided case-by-case.",
    'REW265_PAY_AGENCYPAR': "Whether agency workers get pay-adjacent benefits like recognition, discounts or EAP beyond the statutory Agency Workers Regulations week-12 entitlement.",
    'REW265_PAY_CONTRACTOR': "Whether contractors and freelancers can access employee benefits such as EAP, discounts or training, and how broadly.",
    'REW265_PAY_COUNTEROFFER': "The organisation's stance on matching external offers to retain resigning employees, from never countering to routine counter-offers.",
    'REW265_PAY_EARLYCAREER': "Whether apprentices and graduates progress on a dedicated pay framework separate from the main structure, or on an ad hoc basis.",
    'REW265_PAY_GEOPAY': "Whether pay varies by UK location, from London weighting or multi-zone structures to a single national rate.",
    'REW265_PAY_MGRTRAIN': "Whether line managers receive training or written guidance to support pay decisions ahead of review cycles.",
    'REW265_PAY_PAYCOMMS': "How individual pay review outcomes are conveyed to employees, distinguishing a letter alone from a letter plus a manager conversation.",
    'REW265_PAY_PROMOPAY': "How pay rises on promotion are determined — by a fixed percentage, range position, the new band minimum, or discretion.",
    'REW265_PAY_RANGEMAX': "How the organisation handles pay for staff who have reached or exceeded their band maximum, from lump sums to freezes.",
    'REW265_PAY_SEASONAL': "Whether extra pay rewards staff through seasonal peaks, via a premium during the peak, a completion bonus, or neither.",
    'REW265_TIME_BACKUPCARE': "Whether the organisation provides emergency backup care for children or adult dependants, whether fully funded or via discounted access.",
    'REW265_TIME_BEREAVEDPAT': "Whether the organisation pays above the statutory bereaved-partner paternity entitlement introduced by the Employment Rights Act 2026.",
    'REW265_TIME_DISCONNECT': "Whether the organisation sets expectations limiting out-of-hours contact, via a formal right-to-disconnect policy, informal guidance, or neither.",
    'REW265_TIME_DOMABUSE': "Whether employees facing domestic abuse can access paid leave and a formal support pathway, one, or neither.",
    'REW265_TIME_ELDERCARE': "Whether the organisation offers services helping employees arrange or navigate care for elderly relatives.",
    'REW265_TIME_EXTRADAYS': "Which extra discretionary days off the organisation grants beyond annual leave, such as birthday, wellbeing, or life-event days.",
    'REW265_TIME_FLEXPATTERN': "Which flexible-working patterns the organisation runs as standard, such as compressed hours, core hours, flexitime, or annualised hours.",
    'REW265_TIME_GRANDPARENT': "Whether employees can take paid leave to care for or support a new grandchild.",
    'REW265_TIME_LEAVEDONATE': "Whether a formal scheme lets employees transfer their unused annual leave to colleagues who need it.",
    'REW265_TIME_RTWSUPPORT': "Whether employees returning from extended family leave receive structured support such as coaching and phased return beyond the statutory minimum.",
    'REW265_TIME_SURROGACY': "Whether employees having a child via surrogacy get the same pay and leave as those adopting, fully, partly, or not at all.",
    'REW265_TIME_UNLIMITEDAL': "Whether any group of employees has uncapped annual leave with no fixed entitlement, covering all staff, some roles, or none.",
    'REW265_TIME_WORKATION': "The organisation's approach to employees working remotely from abroad, from uncapped through a day limit or case-by-case to prohibited.",
    'REW26_BEN_PENSION_COST_SHARE': "The employer's pension contribution cost expressed as a percentage of total reward spend, showing pension's share of the reward budget.",
    'REW26_BEN_PENSION_MATCH': "Whether the employer matches employee pension contributions and the maximum matched percentage, from none up to more than 8%.",
    'REW26_BEN_PENSION_TYPE': "Identifies the pension design for the main employee population: defined contribution, defined benefit, or a hybrid of the two.",
    'REW26_BEN_PLSA_QM': "Whether the main scheme's total and employer contributions meet the PLSA quality-mark benchmark of 12% total, including 6% from the employer.",
    'REW26_BEN_SALSAC': "Whether pension contributions are made through salary sacrifice as the default arrangement, exchanging salary for employer contributions to save National Insurance.",
    'REW26_GOV_EU_PTD_PREP': "The organisation's readiness for the EU Pay Transparency Directive, from not started through to fully compliant.",
    'REW26_PAY_JOBEVAL_COVERAGE': "The extent to which a formal job-evaluation or levelling framework covers the workforce, from all roles to none.",
    'REW26_PAY_SKILLS_PAY': "Whether pay is linked to demonstrated skills or capabilities rather than solely to job role, grade or tenure.",
    'REW26_WEL_MH_SUPPORT': "Captures which mental-health provisions the organisation offers, from MH first aiders and counselling to manager training; select all that apply.",
    'REW26_WEL_SCREENING': "Whether the organisation offers health screening or health assessments (e.g. health checks, medicals) to employees.",
    'REW26_WEL_STRATEGY': "Captures whether a written wellbeing strategy exists and, if so, its review cadence, from ad hoc to more than annually.",
    'REW_BEN_038': "Which health and protection benefits the organisation currently provides to employees.",
    'REW_BEN_039': "Whether employees can select or adjust their benefits through a flexible benefits platform.",
    'REW_BEN_041': "The most additional annual leave an employee can typically buy in a year.",
    'REW_BEN_044': "How employees qualify for PMI — all staff, grade-restricted, or subject to a service requirement.",
    'REW_BEN_045': "The death-in-service life assurance sum for most employees, as a multiple of salary.",
    'REW_BEN_046': "Whether income protection is offered, and whether cover is short-term, long-term or both.",
    'REW_BEN_047': "The deferred period before income protection payments start after an employee cannot work.",
    'REW_BEN_048': "The proportion of salary income protection replaces while an employee is unable to work.",
    'REW_BEN_055': "Whether benefit costs are captured centrally within total reward reporting.",
    'REW_BEN_058': "Whether benefits were improved in the past year due to cost-of-living or labour-market pressure.",
    'REW_BEN_100': "The share of the workforce eligible for employer-funded PMI.",
    'REW_BEN_102': "The share of employees taking part in any salary sacrifice arrangement.",
    'REW_BEN_112': "The typical employer pension contribution at each job level, usually as a percentage of pay.",
    'REW_BEN_139': "Which job levels are eligible for employer-provided PMI, across the organisation's level structure.",
    'REW_BEN_FAM_001': "Whether maternity and adoption provision is statutory only or enhances pay, leave, or both.",
    'REW_BEN_FAM_006': "Whether the organisation offers any paid parental leave, going beyond the statutory unpaid parental-leave entitlement.",
    'REW_BEN_FAM_007': "Whether the organisation offers paid carer's leave for staff with caring responsibilities, beyond the statutory unpaid entitlement.",
    'REW_BEN_FAM_008': "Whether emergency or compassionate leave is fully paid, paid at discretion, unpaid, or not specifically provided.",
    'REW_BEN_FAM_009': "Whether the organisation grants paid time off for study or exams, rather than unpaid leave or no specific provision.",
    'REW_BEN_FAM_010': "Whether the organisation offers paid time off for volunteering, as opposed to unpaid leave or no formal provision.",
    'REW_BEN_FAM_011': "Whether extended sabbaticals or career breaks are available, and whether any such leave is paid or unpaid.",
    'REW_BEN_FAM_012': "Whether the organisation offers dedicated paid menopause leave, broader support without specific leave, or no specific provision.",
    'REW_BEN_FLEX_ALLOW_01': "The annual flexible-benefits allowance offered at each employee level, expressed as a percentage of base pay.",
    'REW_BEN_HOL_001': "Typical annual leave for full-time employees, excluding bank holidays; bands run from the 20-day statutory minimum upwards.",
    'REW_BEN_HOL_002': "Whether UK bank holidays are counted within the annual leave allowance, granted on top, or a mix.",
    'REW_BEN_HOL_003': "Whether employees can buy extra annual leave, sell unused days, both, or neither.",
    'REW_BEN_HOL_004': "Whether annual leave entitlement rises with length of service (a service-related holiday uplift).",
    'REW_BEN_HOL_005': "Whether unused annual leave can be carried into the next year, and whether carry-over is standard or limited.",
    'REW_BEN_HOL_006': "The maximum extra annual leave days employees can typically buy; 'Not applicable' means no buy-leave option exists.",
    'REW_BEN_HOL_007': "Whether employees must take annual leave during set shutdown periods, organisation-wide or only in some areas.",
    'REW_BEN_HOL_008': "Whether employees can substitute UK bank holidays for alternative days off, for example to observe other cultural or religious dates.",
    'REW_BEN_PENS_EE_MAX_01': "The highest employee pension contribution rate the scheme permits at each level, not the typical or default rate.",
    'REW_BEN_REM_PAY_001': "How base pay is handled when an employee shifts to remote working — protected, adjusted gradually, adjusted at once, or case-by-case.",
    'REW_BEN_REM_PAY_002': "Which location reference sets base pay for remote roles — home, contracted office, a national rate, or the role's market.",
    'REW_BEN_REM_PAY_003': "The benchmarking basis for remote-role pay — national, regional/local, office comparators, individual, or not benchmarked.",
    'REW_BEN_REM_PAY_004': "Whether pay decisions for remote roles are checked for consistency and fairness, routinely or only in some cases.",
    'REW_BEN_REM_PAY_005': "Whether remote roles attract specific pay premiums, discounts, both, or no location-based adjustment.",
    'REW_BEN_SICK_001': "Whether the organisation pays enhanced occupational sick pay above SSP, only SSP, a combination, or nothing.",
    'REW_BEN_SICK_002': "The typical length of enhanced occupational sick pay before it drops to statutory or nil; longer bands are more generous.",
    'REW_BEN_SICK_004': "Whether a waiting period applies before occupational sick pay starts, and roughly how long it lasts.",
    'REW_BEN_SICK_005': "Whether the eligibility criteria for occupational sick pay are clearly documented — fully, partly, or not.",
    'REW_BEN_SICK_006': "Whether extended or repeated occupational sick pay claims are reviewed before approval, for all cases, some, or none.",
    'REW_FAIR_TIPS_DIST_7d34e570': "How tips and service charges reach employees — paid directly, pooled through a tronc, distributed by the employer, or mixed.",
    'REW_FAI_079': "Whether the organisation runs a gender pay gap analysis at least yearly; 'In development' means it is being introduced.",
    'REW_FAI_081': "Whether pay decisions pass a fairness check, such as calibration or central review, before they take effect.",
    'REW_FAI_082': "Whether departures from standard pay rules are formally recorded with a written justification.",
    'REW_FAI_085': "Whether each annual pay cycle checks outcomes for pay compression and internal equity across comparable roles.",
    'REW_FAI_086': "Whether incentive payouts are analysed by protected characteristic, where data allows and the law permits.",
    'REW_FAI_087': "Whether the organisation has a written pay transparency policy setting out what pay information is shared.",
    'REW_FAI_088': "Whether employees can see the pay ranges for their grade or role family — fully, partly, or not.",
    'REW_FAI_089': "Whether pay ranges are shown on job adverts — for all roles, some roles, or none.",
    'REW_FAI_092': "Whether the organisation has assessed its readiness for pay transparency, reviewing structures, data quality and communications.",
    'REW_FAI_128': "Whether the organisation tests, after pay reviews, that its strongest performers sit above the market median.",
    'REW_FAI_CANCEL_1bbcc629': "Whether hourly-paid workers are compensated for shifts cancelled at short notice — in full, in part, or not at all.",
    'REW_FAI_MIN_HOURS_8518a543': "Whether hourly-paid roles carry guaranteed minimum contracted hours, across all such roles, some, or none.",
    'REW_FAI_STUDY_TIME_93b6ef22': "Whether employees on employer-funded qualifications get paid study time — full leave, limited time, or none.",
    'REW_FAI_TRONC_GROUPS_e5639ac2': "Which role levels take part in the tronc, the pooled arrangement for distributing tips and service charges.",
    'REW_FAI_TRONC_TYPES_b5547658': "Which kinds of gratuities are pooled into the tronc — cash tips, card tips, or service charges.",
    'REW_INC_060': "The performance measures the main bonus or incentive scheme pays against; select all that apply.",
    'REW_INC_061': "The typical weighting between individual and business/company performance in the main bonus scheme, by level.",
    'REW_INC_065': "Whether a gateway metric (such as profit, safety or compliance) must be met before any bonus is paid.",
    'REW_INC_069': "Whether part of the bonus is deferred rather than paid immediately, and how widely deferral applies.",
    'REW_INC_070': "Whether malus provisions allow unpaid or unvested awards to be reduced for misconduct, risk or compliance failures.",
    'REW_INC_071': "Whether clawback provisions allow already-paid awards to be recovered in defined circumstances.",
    'REW_INC_072': "Whether sign-on (joining) bonuses are used, and how routinely — from never to a core attraction tool.",
    'REW_INC_077': "The primary purpose of the organisation's incentives — driving performance, aiding retention, controlling cost, or a mix.",
    'REW_INC_103': "The share of the workforce eligible for a bonus or incentive scheme, from under 10% to over 75%.",
    'REW_INC_104': "The most recent year's average bonus payout expressed as a percentage of the maximum bonus potential.",
    'REW_INC_111': "The on-target bonus opportunity at each level, expressed as a percentage of base salary.",
    'REW_INC_131': "Whether the organisation operates any long-term incentive or equity plan for any part of the workforce.",
    'REW_INC_132': "The primary long-term incentive vehicle offered, spanning equity awards (RSUs, options, performance shares) and cash LTIPs.",
    'REW_INC_133': "Shows which employee levels qualify to participate in long-term incentive plans, recorded level by level.",
    'REW_INC_135': "Whether the organisation runs any sales commission or commission-based incentive scheme; a simple yes/no gate.",
    'REW_INC_136': "The basis on which commission is calculated, from revenue or margin to quota attainment or units sold.",
    'REW_INC_LTI_VALUE_TYP_01': "Target annual long-term incentive award, expressed as a percentage of base pay, at each employee level.",
    'REW_PAY_001': "Whether documented pay ranges exist for permanent roles; 'partially' signals incomplete coverage across roles.",
    'REW_PAY_002': "Whether pay ranges are anchored to a formal job evaluation or grading framework rather than set ad hoc.",
    'REW_PAY_003': "How frequently pay ranges are refreshed against market data, ranging from quarterly to never reviewed.",
    'REW_PAY_005': "The organisation's intended pay positioning against the market.",
    'REW_PAY_006': "How embedded external benchmark data is in pay-setting, from never used to systematic use across multiple sources.",
    'REW_PAY_007': "The external benchmark sources drawn on, spanning consultancy surveys, live tools, recruiter intelligence and peer networks; select all used.",
    'REW_PAY_011': "Whether overtime is paid to any employee population; a simple yes/no with a not-applicable option.",
    'REW_PAY_014': "The standard uplift paid for working UK bank holidays, from no premium up to double time.",
    'REW_PAY_016': "The cash allowances and premiums currently paid, from car and location allowances to shift, weekend and on-call; select all.",
    'REW_PAY_017': "How on-call pay is structured, whether a flat retainer per period, per day, per call-out, or a mix.",
    'REW_PAY_018': "The guaranteed minimum paid when staff are called out, expressed as minimum hours, if any applies.",
    'REW_PAY_019': "Whether, and how often, allowances are folded into base salary at events such as promotion or contract change.",
    'REW_PAY_020': "Whether allowances count as pensionable pay, recorded for each employee level.",
    'REW_PAY_021': "Whether allowances feed into holiday pay calculations; the answer reflects all, some or none of those paid.",
    'REW_PAY_097': "Whether pay rises vary with performance rating, and how strongly, versus a flat award for everyone.",
    'REW_PAY_109': "Maps which role levels qualify for a status car allowance or a lease car.",
    'REW_PAY_TRONC_6db81475': "Whether tips or service charges are shared through a formal tronc, the independent arrangement used to distribute them.",
    'REW_PRO_030': "Whether eligibility to progress depends on performance outcomes, and how consistently that link is applied.",
    'REW_PRO_034': "Whether formal guidelines set the recommended pay positioning to apply when someone is promoted.",
    'REW_PRO_035': "What drives pay progression between annual reviews and promotions, whether performance- or tenure/service-led.",
    'REW_PRO_098': "The usual ceiling on a pay rise awarded at promotion, expressed as a percentage of salary.",
    'REW_Q049530': "The annual business mileage threshold an employee must reach to qualify for a business-need company car.",
    'REW_Q524161': "The notice period the employer must give to end employment, recorded for each employee level.",
    'REW_Q528801': "The overtime pay multiplier applied to the base rate, recorded for each shift type.",
    'REW_Q534581': "The pay-rate multipliers applied to hourly-paid roles across different time bands, such as nights and weekends.",
    'a7ed418e-b057-4b70-ab58-31e897b7c1b6': "Typical total amount paid per employee each year for each type of allowance, in pounds.",
    'b1785613-96ed-4a64-9fd7-762d0ac65f19': "The contractual notice an employee must give to resign, shown for each job level.",
    'fa0f46f6-61e3-41d1-a2d1-3e57483bb1cf': "The typical yearly cash car allowance paid at each job level, in pounds.",
}


def main():
    c = sqlite3.connect(DB); c.row_factory = sqlite3.Row
    changed = missing = 0
    for qid, new in REWRITES.items():
        cur = c.execute("SELECT definition FROM questions WHERE id=?", (qid,)).fetchone()
        if cur is None:
            missing += 1; print("  MISSING:", qid); continue
        if (cur["definition"] or "") == new:
            continue
        changed += 1
        if WRITE:
            c.execute("UPDATE questions SET definition=? WHERE id=?", (new, qid))
    if WRITE:
        c.commit()
    print(("APPLIED" if WRITE else "DRY RUN") + " — %d/%d definitions updated (%d missing)" % (changed, len(REWRITES), missing))
    c.close()


if __name__ == "__main__":
    sys.exit(main() or 0)
