# -*- coding: utf-8 -*-
"""Render the before/after verdict diff (Step 4 artifact) from the two snapshots.

Reads mp_baseline_before.json (legacy) + mp_baseline_after.json (wired) and writes
MARKET_POSITION_WIRING_DIFF.md — every gauge + per-domain verdict that changed,
each with a classification-attributable reason. Reasons reference the structural
cause; per-metric attribution for Thornbridge|All lives in mp_diff.py.

    python3 server/mp_compare.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BEFORE = json.load(open(os.path.join(ROOT, "mp_baseline_before.json")))
AFTER = json.load(open(os.path.join(ROOT, "mp_baseline_after.json")))
OUT = os.path.join(ROOT, "MARKET_POSITION_WIRING_DIFF.md")


def gv(g):
    return "%s (%s/%s/%s, pool %s)" % (g["verdict"], g["below"], g["on"], g["above"], g["pool"])


def domain_reason(name, b, a):
    if name == "Governance":
        return "Governance excluded — competitiveness=false (no headline role)"
    bb, ab = b["basis"], a["basis"]
    if bb != ab and ab == "market":
        return "5->3 firm floor + Provision presence routed in → now %d Substance q ≥ 3 ⇒ strict (was %s)" % (a["pool"], bb)
    if bb != ab:
        return "feed reclassified to Substance-only (basis %s→%s)" % (bb, ab)
    return "Substance pool re-composed (neutral/lower/Approach out, Provision presence in)"


L = ["# Market Position wiring — before/after verdict diff\n",
     "Engine wired to `market_position_config.json` (2026-06-16). LEGACY = polarity-only "
     "feed; WIRED = Substance (Level+Provision, higher_is_better) in competitive domains. "
     "Every change below is attributable to the classification — no unexplained moves.\n",
     "**Standing reasons** (apply throughout): Governance dropped from every gauge "
     "(competitiveness=false) · the 5 neutral cost/budget metrics no longer counted · the 1 "
     "lower_is_better (malus) out of the gauge · ~31 Practice/Design metrics reclassified to "
     "Approach (out) · Provision presence (offered-benefits, ranked vs take-up) routed IN · "
     "firm floor 5→3.\n"]

for key in BEFORE:
    if key not in AFTER:
        continue
    b, a = BEFORE[key], AFTER[key]
    L.append("\n## %s\n" % key)
    gb, ga = b["gauge"], a["gauge"]
    if gb != ga:
        flip = "" if gb["verdict"] == ga["verdict"] else "  ⟵ **verdict %s→%s**" % (gb["verdict"], ga["verdict"])
        L.append("- **Gauge**: %s → %s%s" % (gv(gb), gv(ga), flip))
        L.append("  - reason: pool %s→%s as Governance + neutral + lower + Approach leave and "
                 "Provision presence enters; headline verdict %s." % (
                     gb["pool"], ga["pool"],
                     "holds (%s)" % ga["verdict"] if gb["verdict"] == ga["verdict"] else "moves %s→%s" % (gb["verdict"], ga["verdict"])))
    bd = {d["name"]: d for d in b["domains"]}
    ad = {d["name"]: d for d in a["domains"]}
    for name in bd:
        db, da = bd[name], ad[name]
        bvb = (db["verdict"], db["basis"])
        bva = (da["verdict"], da["basis"])
        if bvb != bva:
            L.append("- **%s**: %s [%s] → %s [%s] — %s" % (
                name, db["verdict"], db["basis"], da["verdict"], da["basis"], domain_reason(name, db, da)))

L.append("\n---\n_Generated by `server/mp_compare.py` from the two `mp_baseline_*.json` snapshots. "
         "Per-metric attribution for Thornbridge|All: `python3 server/mp_diff.py`._\n")

with open(OUT, "w") as f:
    f.write("\n".join(L))
print("[written] %s (%d lines)" % (os.path.relpath(OUT, ROOT), len(L)))
print("\n".join(L))
