"""Refresh-cadence policy — when does an answered metric need re-confirming?

The cadences are RULED in data/metric_refresh_register.json (generated by
gen_refresh_register.py, reviewed 2026-08-04): annual=12 / benefit=18 /
structural=24 months, plus per-metric overrides. This module only reads the
register and computes due-ness from answers.submitted_at.

Two invariants the design leans on:
  * answers_history is append-only — every accepted value is preserved, so a
    refresh (even re-confirming the same value) never loses the prior answer.
  * answers.submitted_at is bumped on every accepted save, so it is the
    staleness clock. A question's clock is the OLDEST of its rows (a matrix
    is only fresh when all of it is).

Refresh is a nudge, never a gate: stale answers keep counting in the
benchmark and completion. The flag just asks the member to look again.
"""
import json
import os

REGISTER_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                             "..", "data", "metric_refresh_register.json")
_cache = {"mtime": None, "months": {}, "classes": {}}

# fallback mirror of the register's class rules — a question added after the
# register was generated still gets a cadence
_QUANT_UNITS = ("currency", "percentage", "weeks")
_DEFAULTS = {"annual": 12, "benefit": 18, "structural": 24}


def _register():
    try:
        mt = os.path.getmtime(REGISTER_PATH)
    except OSError:
        return _cache
    if _cache["mtime"] != mt:
        try:
            with open(REGISTER_PATH) as f:
                reg = json.load(f)
            _cache["months"] = {qid: m["months"] for qid, m in (reg.get("metrics") or {}).items()}
            _cache["classes"] = reg.get("classes") or dict(_DEFAULTS)
            _cache["mtime"] = mt
        except (ValueError, OSError):
            pass  # malformed edit keeps the last good register
    return _cache


def months_for(q):
    """Cadence in months for a question object (register first, class rule fallback)."""
    reg = _register()
    m = reg["months"].get(q.id)
    if m:
        return m
    classes = reg["classes"] or _DEFAULTS
    if q.category == "metric" or (q.unit_type or "none") in _QUANT_UNITS:
        return classes.get("annual", 12)
    if q.category == "benefit":
        return classes.get("benefit", 18)
    return classes.get("structural", 24)


def refresh_state(conn, org_id, snapshot_id, questions):
    """{qid: {"last": iso-datetime, "due": bool, "months": n}} for every
    answered question in `questions` ({qid: Question}, the caller's visible set).

    due = the question's OLDEST answer row predates its cadence cutoff.
    Computed against the same clock that stamps submitted_at (sqlite UTC now),
    so a freshly saved answer can never read as due.
    """
    oldest = {r["question_id"]: r["m"] for r in conn.execute(
        "SELECT question_id, MIN(submitted_at) m FROM answers "
        "WHERE org_id=? AND snapshot_id=? GROUP BY question_id",
        (org_id, snapshot_id))}
    cutoffs = {}
    out = {}
    for qid, last in oldest.items():
        q = questions.get(qid)
        if q is None:
            continue
        months = months_for(q)
        if months not in cutoffs:
            cutoffs[months] = conn.execute(
                "SELECT datetime('now', ?) c", ("-%d months" % months,)).fetchone()["c"]
        out[qid] = {"last": last, "due": bool(last and last <= cutoffs[months]),
                    "months": months}
    return out
