# -*- coding: utf-8 -*-
"""Curated priors and drivers for the seed-data regeneration.

Every entry follows the core rule: a non-uniform prior exists ONLY where a
moderate real-world baseline can be named and defended. `source` records the
basis; anything not from a published norm is marked "estimate" (practitioner
judgement of mainstream UK practice), never presented as a published statistic.

Weight keys are case-insensitive substring/regex patterns resolved against the
question's actual option labels at run time; the engine validates that every
pattern matches at least one option and every option gets a weight.

Driver vocabulary (applied by the engine):
  tilt:F=k        score-ladder tilt by the org's latent formality/maturity F
  anchor:<name>   question-specific deterministic/strong modulation (coded)
"""

# --------------------------------------------------------------- selects ----
# qid -> {w: {pattern: weight}, rest: default-weight, tilt: k, anchor: name,
#         drivers: human-readable driver map line, rationale, source}
SELECT_PRIORS = {
    "PROP_8e0b6316": {  # main pay review cycle frequency
        "w": {"^Annually": 0.80, "Twice": 0.07, "Quarterly": 0.02, "ad hoc": 0.06,
              "Not applicable": 0.02, "Don't know": 0.03},
        "tilt": 0.5,
        "drivers": "FTE_Band/F: small informal orgs shift toward ad hoc; large toward Annually",
        "rationale": "Annual pay reviews are the overwhelming UK norm; CIPD/XpertHR reward surveys consistently show ~80-90% of organisations on an annual cycle.",
        "source": "CIPD/XpertHR-style norm",
    },
    "PROP_dff9a2a5": {  # proportion receiving base pay increase
        "w": {"95%–100%": 0.38, "75%–94%": 0.28, "50%–74%": 0.14, "25%–49%": 0.08,
              "1%–24%": 0.05, "^0%$": 0.02, "Not measured": 0.05},
        "anchor": "pay_rise_budget",
        "drivers": "Budget_Flexibility: Tight shifts down a band; Public Sector/unionised toward 95-100% (spine points)",
        "rationale": "In a normal review year most UK employers award increases to most staff; across-the-board or near-universal awards are the norm, especially where pay spines apply.",
        "source": "CIPD reward practice norm",
    },
    "PROP_e1d1e604": {  # off-cycle increases
        "w": {"0–5%": 0.36, "6–10%": 0.30, "11–20%": 0.18, "21–30%": 0.06,
              "31%\\+": 0.02, "Not measured": 0.05, "Don't know": 0.03},
        "anchor": "offcycle_turnover",
        "drivers": "Turnover_Band/Talent_Competition: high-churn, hot-market orgs make more off-cycle awards",
        "rationale": "Off-cycle increases are exception-based for most employers (retention/counter-offer), typically affecting a small minority of staff.",
        "source": "estimate",
    },
    "PROP_36b990f9": {  # typical employer pension contribution band
        "w": {"<3%": 0.02, "3%–4%": 0.27, "5%–7%": 0.39, "8%–10%": 0.17, "11%\\+": 0.08,
              "Varies widely": 0.04, "Not applicable": 0.005, "Don't know": 0.025},
        "anchor": "pension_band",
        "drivers": "Ownership=Public Sector -> 11%+ (DB schemes); FTE_Band up -> higher band; derived from same latent value as the by-level pension matrices",
        "rationale": "Auto-enrolment floor is 3% employer; private-sector typical employer contributions cluster around 4-8% (ONS pension participation data), public sector materially higher.",
        "source": "ONS/auto-enrolment baseline",
    },
    "SICK_01_88ce3d5c": {  # company sick pay above SSP? yes/no
        "w": {"^Yes": 0.72, "^No": 0.28},
        "anchor": "osp_offer",
        "drivers": "F/FTE_Band up -> Yes; high-frontline hospitality/retail down",
        "rationale": "A clear majority of UK employers pay some occupational sick pay above SSP; minority statutory-only, concentrated in smaller and high-frontline employers.",
        "source": "CIPD absence-survey-style norm",
    },
    "REW_BEN_SICK_001": {  # OSP vs SSP detail
        "w": {"Statutory sick pay only": 0.24, "Enhanced occupational": 0.45,
              "Combination": 0.26, "No sick pay": 0.01, "Don't know": 0.04},
        "anchor": "osp_consistency",
        "drivers": "Consistent with SICK_01; statutory-only orgs answer 'Statutory sick pay only'",
        "rationale": "Mirror of SICK_01 with the enhanced majority split between enhanced-only and enhanced+SSP combination.",
        "source": "CIPD absence-survey-style norm",
    },
    "REW_BEN_SICK_002": {  # enhanced OSP duration
        "w": {"None \\(statutory": 0.24, "Up to 4 weeks": 0.18, "5-12 weeks": 0.28,
              "13-26 weeks": 0.22, "More than 26": 0.05, "Don't know": 0.03},
        "anchor": "osp_consistency_dur",
        "drivers": "Tied to OSP offer; larger/public orgs longer durations (26-week full/half-pay schemes)",
        "rationale": "Common UK schemes run weeks-to-months, with public-sector style 6-month full/half pay at the generous end.",
        "source": "estimate",
    },
    "REW_BEN_SICK_004": {  # waiting period before OSP
        "w": {"No waiting period": 0.36, "up to 3 days": 0.27, "more than 3 days": 0.11,
              "Not applicable": 0.22, "Don't know": 0.04},
        "anchor": "osp_consistency_wait",
        "drivers": "Tied to OSP offer (statutory-only -> Not applicable); waiting days commoner in frontline-heavy orgs",
        "rationale": "Where OSP exists most schemes pay from day one or after SSP-style waiting days; statutory-only employers map to Not applicable.",
        "source": "estimate",
    },
    "CONT_01_7e020202": {  # probation length
        "w": {"No probation": 0.04, "Up to 1 month": 0.02, "^2 months": 0.05,
              "^3 months": 0.39, "4–5 months": 0.05, "^6 months": 0.36,
              "More than 6": 0.03, "Varies": 0.05, "Don't know": 0.01},
        "drivers": "FTE_Band up -> 6 months commoner; small orgs more 3-month/varies",
        "rationale": "Three and six months are the two standard UK probation lengths, between them covering the large majority of employers.",
        "source": "well-understood market practice",
    },
    "REW_FAI_079": {  # gender pay gap analysis at least annually
        "w": {"^Yes": 0.45, "In development": 0.15, "^No": 0.40},
        "anchor": "gpg_250",
        "drivers": "FTE_Band: 250+ -> Yes ~0.93 (statutory reporting duty); <250 voluntary minority",
        "rationale": "Gender pay gap reporting is mandatory for 250+ employee employers (gov.uk), so analysis is near-universal there and a voluntary minority practice below the threshold.",
        "source": "gov.uk statutory duty",
    },
    "REW_BEN_HOL_001": {  # annual leave days excl. BH
        "w": {"Statutory minimum": 0.10, "21-24 days": 0.22, "25-27 days": 0.43,
              "28-30 days": 0.17, "More than 30": 0.05, "Don't know": 0.03},
        "anchor": "leave_days",
        "drivers": "Ownership=Public/Charity & FTE_Band up -> higher bands; small founder-led -> lower",
        "rationale": "25 days plus bank holidays is the modal UK private-sector entitlement; public sector commonly 27-30+.",
        "source": "XpertHR/Brightmine-style norm",
    },
    "REW_BEN_HOL_003": {  # buy/sell leave
        "w": {"both buy and sell": 0.15, "buy only": 0.18, "sell only": 0.02,
              "^No": 0.61, "Don't know": 0.04},
        "tilt": 0.5,
        "drivers": "FTE_Band/flex-benefits maturity up -> buy schemes commoner",
        "rationale": "Holiday purchase schemes are a sizeable-minority practice (roughly a third of employers, skewed large); selling is much rarer.",
        "source": "estimate",
    },
    "REW_BEN_HOL_004": {  # service-linked extra leave
        "w": {"^Yes": 0.55, "^No": 0.42, "Don't know": 0.03},
        "drivers": "Light size effect only",
        "rationale": "Length-of-service holiday accrual is mainstream, roughly half of employers.",
        "source": "estimate",
    },
    "REW_BEN_HOL_005": {  # carry-over
        "w": {"standard carry-over": 0.34, "limited carry-over": 0.46,
              "forfeited": 0.17, "Don't know": 0.03},
        "drivers": "None strong — baseline with light F modulation",
        "rationale": "Most employers allow some carry-over, typically capped (commonly 5 days); pure use-it-or-lose-it is the minority.",
        "source": "estimate",
    },
    "REW_BEN_HOL_006": {  # max days purchasable
        "w": {"Not applicable": 0.62, "Up to 5 days": 0.22, "6-10 days": 0.13,
              "More than 10": 0.01, "Don't know": 0.02},
        "anchor": "buy_leave_consistency",
        "drivers": "Conditional on REW_BEN_HOL_003: no buy scheme -> Not applicable; else typically one week",
        "rationale": "Where purchase schemes exist the cap is most commonly one working week.",
        "source": "estimate",
    },
    "REW_BEN_041": {  # max additional leave purchasable (alt form)
        "w": {"1–5 days": 0.24, "6-10 days|6–10 days": 0.13, "11\\+ days": 0.01,
              "Not offered": 0.62},
        "anchor": "buy_leave_consistency2",
        "drivers": "Conditional on REW_BEN_HOL_003 like REW_BEN_HOL_006",
        "rationale": "Same baseline as REW_BEN_HOL_006.",
        "source": "estimate",
    },
    "REW_BEN_HOL_007": {  # shutdown periods
        "w": {"mandatory shutdown": 0.10, "some parts": 0.10, "^No": 0.77, "Don't know": 0.03},
        "anchor": "shutdown_sector",
        "drivers": "Sector: Manufacturing/Construction -> shutdowns commoner (Christmas/summer closures)",
        "rationale": "Mandatory shutdowns are a minority practice concentrated in manufacturing/construction (seasonal closures).",
        "source": "well-understood market practice",
    },
    "REW_INC_103": {  # bonus eligibility proportion
        "w": {"<10%": 0.13, "10–24%": 0.11, "25–49%": 0.11, "50–74%": 0.13,
              "75%\\+": 0.33, "None": 0.19},
        "anchor": "bonus_eligibility",
        "drivers": "Ownership: PLC/PE -> broad eligibility; Public Sector/Charity -> None dominates; drives the bonus matrices",
        "rationale": "Most private-sector employers operate some bonus and increasingly broad-based eligibility; bonuses remain rare in public sector and charities.",
        "source": "CIPD reward-survey-style norm",
    },
    "WEL_MEN_021": {  # EAP offered
        "w": {"^Yes": 0.80, "In development": 0.06, "^No": 0.14},
        "tilt": 0.7,
        "drivers": "FTE_Band/F up -> Yes (EAPs near-universal in large employers)",
        "rationale": "EAPs are one of the most prevalent UK benefits, around three-quarters or more of employers and near-universal among large ones.",
        "source": "CIPD/EAPA-style norm",
    },
    "WEL_MH_02": {  # confidential mental-health support
        "w": {"most employees": 0.74, "some employee groups": 0.14, "^No": 0.12},
        "tilt": 0.6,
        "drivers": "Follows EAP prevalence; F up -> most employees",
        "rationale": "Tracks EAP/mental-health support prevalence.",
        "source": "CIPD-style norm",
    },
    "REW_BEN_045": {  # life assurance multiple
        "w": {"^1×": 0.09, "^2×": 0.19, "^3×": 0.16, "4× or more": 0.13, "Not offered": 0.43},
        "anchor": "richness_updown",
        "drivers": "FTE_Band/Budget_Flexibility up -> offered and higher multiples",
        "rationale": "Group life cover reaches roughly half of employers (skewed to mid/large), with 2-4x salary the standard multiples.",
        "source": "estimate",
    },
    "REW_PAY_001": {  # formal pay ranges for all roles
        "w": {"^Yes": 0.42, "Partially": 0.32, "^No": 0.26},
        "tilt": 1.3,
        "drivers": "F (HR_Maturity/FTE_Band/Ownership): formal ranges scale strongly with size and governance",
        "rationale": "Formal pay structures are majority practice among established/larger employers and uncommon in small founder-led firms; the blend across the seed mix sits near half.",
        "source": "CIPD reward-survey-style norm",
    },
    "REW_PAY_002": {  # ranges linked to job evaluation
        "w": {"^Yes": 0.38, "In development": 0.18, "^No": 0.44},
        "tilt": 1.2,
        "drivers": "F up -> documented evaluation/grading frameworks",
        "rationale": "Job-evaluated grading is standard in large/public organisations, rare in small ones.",
        "source": "well-understood market practice",
    },
    "REW_PAY_003": {  # how often ranges refreshed
        "w": {"Quarterly": 0.02, "Biannually": 0.06, "^Annually": 0.45, "Ad hoc": 0.32, "Not reviewed": 0.15},
        "tilt": 0.8,
        "drivers": "F up -> annual refresh; low-F -> ad hoc/not reviewed",
        "rationale": "Annual market refresh is the standard cadence where structures exist; ad hoc dominates otherwise.",
        "source": "well-understood market practice",
    },
    "REW_PAY_006": {  # external benchmark data use (5-level ladder)
        "w": {"Not used": 0.15, "occasionally": 0.27, "regularly": 0.26,
              "consistently": 0.22, "systematically": 0.10},
        "tilt": 1.2,
        "drivers": "F: data-led pay management scales with maturity and size",
        "rationale": "Most employers use some external pay data; systematic multi-source use is confined to the sophisticated end.",
        "source": "CIPD reward-survey-style norm",
    },
    "PROP_fe1a29ec": {  # external benchmarking at least annually y/p/n
        "w": {"^Yes": 0.52, "Partially": 0.26, "^No": 0.22},
        "tilt": 1.0,
        "drivers": "Consistent with REW_PAY_006 via F",
        "rationale": "As REW_PAY_006.",
        "source": "CIPD reward-survey-style norm",
    },
    "REW_FAI_087": {  # documented pay transparency approach
        "w": {"^Yes": 0.17, "In development": 0.28, "^No": 0.55},
        "tilt": 0.9,
        "drivers": "F/size up; EU directive horizon pushes 'In development'",
        "rationale": "Documented pay transparency remains minority practice in the UK, with a sizeable in-development cohort ahead of EU-style requirements.",
        "source": "estimate",
    },
    "REW_FAI_088": {  # employee access to pay ranges
        "w": {"^Yes": 0.30, "Partial": 0.30, "^No": 0.40},
        "tilt": 0.9,
        "drivers": "Follows pay-structure formality (F)",
        "rationale": "Sharing ranges with employees lags having ranges; minority-to-mixed practice.",
        "source": "estimate",
    },
    "REW_FAI_089": {  # publish ranges on adverts
        "w": {"All roles": 0.14, "Some roles": 0.33, "^No": 0.53},
        "drivers": "Public Sector -> All roles (standard practice); private minority",
        "anchor": "advert_ranges_public",
        "rationale": "Salary-on-advert is standard in the public sector and a growing minority elsewhere.",
        "source": "well-understood market practice",
    },
    "PRO_COLLBARG_0a071dd7": {  # collective bargaining used
        "w": {"pay and core terms": 0.22, "limited terms": 0.10, "^No": 0.68},
        "anchor": "union_bargaining",
        "drivers": "Workforce_Unionised_%: >40% -> pay+core dominant; ~0% -> No (ONS: ~25% coverage economy-wide, concentrated in public sector)",
        "rationale": "ONS trade-union statistics put collective-bargaining coverage near a quarter of employees, heavily concentrated in the public sector and unionised industries.",
        "source": "ONS trade union statistics",
    },
    "PROP_eda6a130": {  # engaged in collective bargaining last 12m
        "w": {"^Yes": 0.25, "^No": 0.55, "Not applicable": 0.17, "Don't know": 0.03},
        "anchor": "union_bargaining2",
        "drivers": "Workforce_Unionised_% as above",
        "rationale": "As PRO_COLLBARG.",
        "source": "ONS trade union statistics",
    },
    "MET_1fa3fa15": {  # sickness absence rate banded
        "w": {"^0%$": 0.01, "1%–2%": 0.20, "2%–3%": 0.30, "3%–4%": 0.24, "4%–5%": 0.13,
              "5%–6%": 0.07, "6%–8%": 0.03, "8%–10%": 0.01, "Over 10%": 0.01},
        "anchor": "absence_profile",
        "drivers": "Workforce_Frontline_% and Public Sector -> higher bands; office-based -> lower",
        "rationale": "ONS sickness-absence rate runs ~2% economy-wide with higher rates in public sector, health and frontline-heavy work.",
        "source": "ONS sickness absence statistics",
    },
    "WEL_WOR_054": {  # absence rate (coarser bands)
        "w": {"<2%": 0.27, "2–3%": 0.33, "3–4%": 0.22, "4–6%": 0.12, "6%\\+": 0.03,
              "Not calculated": 0.03},
        "anchor": "absence_profile",
        "drivers": "As MET_1fa3fa15 (kept consistent per org)",
        "rationale": "As MET_1fa3fa15.",
        "source": "ONS sickness absence statistics",
    },
    "MET_7f79a965": {  # voluntary turnover banded
        "w": {"^0%$": 0.01, "1%–5%": 0.14, "5%–10%": 0.30, "10%–15%": 0.28, "15%–20%": 0.15,
              "20%–25%": 0.07, "25%–30%": 0.03, "Over 30%": 0.02},
        "anchor": "turnover_registry",
        "drivers": "Turnover_Band (registry) anchors the reported band directly",
        "rationale": "UK voluntary turnover typically averages low-to-mid teens; the registry already assigns each org a turnover band, which the answer must echo.",
        "source": "registry-anchored; CIPD resourcing norm",
    },
    "ATTR_OE_04": {  # early attrition (first-year) banded
        "w": {"0%–2%": 0.06, "2.1%–5%": 0.18, "5.1%–10%": 0.32, "10.1%–15%": 0.24,
              "15.1%–25%": 0.13, "More than 25%": 0.04, "Not tracked": 0.03},
        "anchor": "early_attrition",
        "drivers": "Scales with registry Turnover_Band",
        "rationale": "First-year leaver rates typically run somewhat above all-staff turnover; anchored to each org's turnover band.",
        "source": "estimate (registry-anchored)",
    },
    "ONB_03": {  # 90-day voluntary attrition
        "w": {"0–2%": 0.25, "3–5%": 0.36, "6–10%": 0.24, "11–15%": 0.09, "16–20%": 0.03,
              "20%\\+": 0.01, "Don't know": 0.02},
        "anchor": "early_attrition90",
        "drivers": "Scales with registry Turnover_Band",
        "rationale": "Very-early attrition is a small single-digit share for most employers, higher in high-churn frontline sectors.",
        "source": "estimate (registry-anchored)",
    },
    "ATTR_HE_07": {  # % passing probation first time
        "w": {"0%–49%": 0.01, "50%–64%": 0.02, "65%–79%": 0.07, "80%–89%": 0.26,
              "90%–94%": 0.31, "95%–100%": 0.28, "Not tracked": 0.05},
        "drivers": "Light F effect (tracking); high churn shifts down slightly",
        "rationale": "The overwhelming majority of UK new hires pass probation; failure/extension is exceptional.",
        "source": "well-understood market practice",
    },
    "EXT_REW_GAP_009": {  # office attendance for remote-capable roles
        "w": {"Fully remote": 0.05, "Less than once a month": 0.07, "1–2 days per week": 0.38,
              "3 or more days": 0.28, "varies widely": 0.18, "Don't know": 0.04},
        "drivers": "Light only — hybrid norms are broadly cross-sector for desk-based roles",
        "rationale": "ONS/industry surveys show hybrid (2-3 office days) as the dominant pattern for remote-capable UK roles; fully-remote is a small minority.",
        "source": "ONS hybrid-working statistics",
    },
    "WEL_FLE_030": {  # access to flexible working
        "w": {"formal policy": 0.58, "informal": 0.30, "^No": 0.12},
        "tilt": 0.9,
        "drivers": "F/size -> formal policy (day-one statutory right to request since 2024)",
        "rationale": "Statutory right-to-request plus mainstream practice makes some flexible-working access near-universal; formality scales with size.",
        "source": "gov.uk statutory context",
    },
    "WEL_FLE_031": {  # offered across all roles where possible
        "w": {"^Yes": 0.34, "Some roles": 0.52, "^No": 0.14},
        "drivers": "High Workforce_Frontline_% -> Some roles (operational constraint)",
        "anchor": "flex_frontline",
        "rationale": "Frontline/shift operations constrain flexibility to role subsets in most organisations.",
        "source": "well-understood market practice",
    },
    "REW_PAY_011": {  # do you pay overtime
        "w": {"^Yes": 0.62, "^No": 0.28, "Not applicable": 0.10},
        "anchor": "overtime_frontline",
        "drivers": "Workforce_Shift_%/Frontline_% high -> Yes ~0.9; low-frontline professional firms -> No",
        "rationale": "Paid overtime is standard for hourly/shift populations and uncommon for salaried professional ones.",
        "source": "well-understood market practice",
    },
    "OT_03_1a68c68a": {  # TOIL offered
        "w": {"^Yes": 0.55, "^No": 0.45},
        "drivers": "Public/Charity -> TOIL commoner; light elsewhere",
        "anchor": "toil_public",
        "rationale": "TOIL is widespread, particularly in public/third sector where paid overtime is restricted.",
        "source": "estimate",
    },
    "REW_BEN_FAM_001": {  # maternity/adoption vs statutory
        "w": {"Statutory pay only": 0.36, "Enhanced pay": 0.34, "Enhanced leave only": 0.05,
              "Combination": 0.21, "Don't know": 0.04},
        "anchor": "richness_updown",
        "drivers": "FTE_Band/Ownership (public/large -> enhanced); small/frontline -> statutory",
        "rationale": "Roughly half of UK employers enhance maternity pay, strongly size-graded.",
        "source": "CIPD-style norm",
    },
    "REW_BEN_FAM_002": {  # weeks of enhanced maternity pay
        "w": {"None": 0.36, "1-12 weeks": 0.27, "13-26 weeks": 0.25, "27-39 weeks": 0.08,
              "40-52 weeks": 0.02, "Don't know": 0.02},
        "anchor": "maternity_consistency",
        "drivers": "Conditional on REW_BEN_FAM_001 (statutory-only -> None)",
        "rationale": "Where enhanced, 6-26 weeks of enhanced pay is the common range.",
        "source": "estimate",
    },
    "REW_BEN_FAM_006": {  # paid parental beyond statutory
        "w": {"paid leave is provided": 0.34, "statutory unpaid only|^No": 0.62, "Don't know": 0.04},
        "anchor": "richness_updown",
        "drivers": "Size/richness up",
        "rationale": "A growing minority offer paid parental leave beyond statutory.",
        "source": "estimate",
    },
    "REW_BEN_102": {  # salary sacrifice participation
        "w": {"<10%": 0.24, "10–24%": 0.26, "25–49%": 0.16, "50%\\+": 0.11, "Not offered": 0.23},
        "anchor": "salsac_size",
        "drivers": "FTE_Band up -> offered and higher participation (pension salary sacrifice standard in large employers)",
        "rationale": "Pension salary sacrifice is standard among large employers and rarer among small ones; participation where offered is broad.",
        "source": "well-understood market practice",
    },
    "REW_PAY_TRONC_6db81475": {  # tronc operated
        "w": {"^Yes": 0.06, "^No": 0.10, "Not applicable": 0.84},
        "anchor": "tronc_sector",
        "drivers": "Sector: Hospitality -> Yes dominant (tipping economy); others Not applicable",
        "rationale": "Troncs exist where tips exist — hospitality and parts of leisure; meaningless elsewhere.",
        "source": "well-understood market practice",
    },
    "PRO_GOV_TRONC_IND_3cc52941": {
        "w": {"independently managed": 0.05, "Partially": 0.03, "employer-managed": 0.03,
              "Not applicable": 0.89},
        "anchor": "tronc_sector_dep",
        "drivers": "Conditional on REW_PAY_TRONC (no tronc -> Not applicable)",
        "rationale": "Conditional detail of the tronc question; independent troncmasters are the compliant norm.",
        "source": "well-understood market practice",
    },
    "REW_FAI_TRONC_TYPES_b5547658": {
        "w": {"Card tips": 0.06, "Service charges": 0.05, "Cash tips": 0.03, "Not applicable": 0.86},
        "anchor": "tronc_sector_dep",
        "drivers": "Conditional on REW_PAY_TRONC",
        "rationale": "Card tips/service charge dominate modern tronc flows.",
        "source": "well-understood market practice",
    },
    "PROP_8c304d7c": {  # EAP utilisation
        "w": {"0%–2%": 0.13, "3%–5%": 0.28, "6%–8%": 0.24, "9%–12%": 0.17, "13%\\+": 0.06,
              "Not measured": 0.12},
        "drivers": "Light F effect on measurement",
        "rationale": "Industry-cited EAP utilisation typically runs mid-single-digits to ~12%.",
        "source": "EAPA-style industry norm",
    },
    "REW_BEN_044": {  # PMI eligibility rules (select)
        "w": {"All employees": 0.17, "Grade/level restricted": 0.20, "Contract type": 0.02,
              "Service length": 0.03, "Post-probation": 0.13, "Not offered": 0.45},
        "anchor": "pmi_consistency",
        "drivers": "Conditional on PMI in REW_BEN_038; grade-restriction the classic pattern; drives PMI matrices",
        "rationale": "PMI reaches roughly half of employers (size-graded) and is classically grade-restricted or post-probation.",
        "source": "CIPD/Brightmine-style norm",
    },
}

# ------------------------------------------------------------ multi-select ---
# qid -> {opts: {pattern: base_prevalence}, rest: default, anchor, drivers,
#         rationale, source, none_pattern}
MULTI_PRIORS = {
    "ALLOW_01": {
        "opts": {"Car allowance": 0.34, "Shift allowance": 0.30, "On-call": 0.32,
                 "Location|cost-of-living": 0.16, "Travel": 0.24, "Mobile|phone": 0.34,
                 "Meal": 0.10, "Homework|home-work|Home work": 0.14, "First aid|first-aid": 0.28,
                 "Other": 0.08, "^None": 0.0},
        "rest": 0.10, "none_pattern": "^None",
        "anchor": "allowances_profile",
        "drivers": "Workforce_Shift_% -> shift/on-call; HQ_Region London -> location allowance; richness -> car/mobile",
        "rationale": "Allowance prevalence follows workforce shape: shift/on-call pay where shift work exists; car allowances for managerial/field populations; location weighting in London.",
        "source": "well-understood market practice",
    },
    "REW_PAY_016": {
        "opts": {"Car allowance": 0.34, "London weighting|location": 0.16, "Shift allowance": 0.30,
                 "Night premium": 0.24, "Weekend premium": 0.22, "Bank holiday": 0.26,
                 "On-call": 0.32, "Standby": 0.14, "Call-out|Call out": 0.18, "Tool": 0.07,
                 "Uniform|clothing": 0.10, "Meal": 0.09, "Travel": 0.22, "Mobile|phone": 0.32,
                 "First aid": 0.27, "Fire warden|warden": 0.12, "Other": 0.06, "^None": 0.0},
        "rest": 0.08, "none_pattern": "^None",
        "anchor": "allowances_profile",
        "drivers": "As ALLOW_01 — premiums driven by Workforce_Shift_%, kept consistent with ALLOW_01 and the allowance-value matrix",
        "rationale": "As ALLOW_01, with night/weekend/bank-holiday premiums tied to shift operations.",
        "source": "well-understood market practice",
    },
    "REW_BEN_038": {
        "opts": {"Private Medical Insurance": 0.50, "cash plan": 0.28, "Dental": 0.22,
                 "Life assurance": 0.55, "Income protection": 0.30, "Critical illness": 0.20,
                 "Employee Assistance|EAP": 0.80, "Eye care|eyecare": 0.55, "Cycle": 0.48,
                 "Gym|fitness": 0.32, "Season ticket": 0.20, "Electric vehicle|EV": 0.18,
                 "Will writing|will-writing": 0.12, "Discount": 0.40, "Health screening|screening": 0.25,
                 "Flu": 0.30, "None": 0.0},
        "rest": 0.15, "none_pattern": "^None",
        "anchor": "benefits_richness",
        "drivers": "FTE_Band + Budget_Flexibility (richness R) scale the odds of every benefit; PMI selection drives PMI-dependent questions",
        "rationale": "Core-benefit prevalence ordering (EAP and life assurance high; PMI ~half, size-graded; cash plans/dental mid; niche items low) reflects published UK benefit surveys.",
        "source": "CIPD/Brightmine-style norm",
    },
    "EXT_REW_GAP_005": {
        "opts": {"^5 years": 0.42, "^10 years": 0.70, "^15 years": 0.30, "^20 years": 0.45,
                 "25 years": 0.50, "Other": 0.08, "Not applicable": 0.0, "Don't know": 0.0},
        "rest": 0.1, "none_pattern": "Not applicable",
        "anchor": "longservice_dep",
        "drivers": "Conditional on the long-service-scheme question; decade milestones dominate",
        "rationale": "Where long-service awards exist, 10/20/25-year milestones are the classic pattern.",
        "source": "well-understood market practice",
    },
    "EXT_REW_GAP_011": {
        "opts": {"^Equipment": 0.50, "IT equipment only": 0.22, "Broadband": 0.10,
                 "Utility": 0.04, "^None": 0.0, "Don't know": 0.0},
        "rest": 0.05, "none_pattern": "^None",
        "anchor": "homework_lowfrontline",
        "drivers": "Low Workforce_Frontline_% (desk-based) -> equipment provision standard; high-frontline -> None",
        "rationale": "Employers routinely provide equipment for home workers; ongoing broadband/utility funding is rare.",
        "source": "well-understood market practice",
    },
    "PRO_UNIONSCOPE_53b16ffb": {
        "opts": {"No union recognition": 0.0, "Frontline|hourly": 0.0, "Operations|manufacturing|logistics": 0.0,
                 "Professional|office": 0.0, "Engineering|technical|Specialist": 0.0, "All employees": 0.0,
                 "Management": 0.0, "Other": 0.0},
        "rest": 0.0, "none_pattern": "No union recognition",
        "anchor": "union_scope",
        "drivers": "Workforce_Unionised_% determines recognition and which groups (frontline/ops first; 'all employees' at very high coverage)",
        "rationale": "Recognition follows union density: frontline/operational groups are organised first; whole-workforce agreements only at high density (public-sector pattern).",
        "source": "ONS trade union statistics",
    },
    "HR_OP_08": {
        "opts": {"Payroll": 0.52, "Recruitment": 0.18, "HR administration": 0.10,
                 "Learning admin": 0.08, "Employee relations": 0.04, "Benefits administration": 0.20,
                 "Other": 0.05, "^None": 0.0},
        "rest": 0.05, "none_pattern": "^None",
        "anchor": "outsourcing_size",
        "drivers": "Small orgs outsource payroll more; very large bring it in-house or to shared services",
        "rationale": "Payroll is the most commonly outsourced HR service in the UK (roughly half of employers); ER almost never is.",
        "source": "well-understood market practice",
    },
    "REW_INC_060": {
        "opts": {"Company financial": 0.80, "Business unit": 0.40, "Individual objectives": 0.62,
                 "Performance rating": 0.42, "Revenue / sales|Revenue|sales targets": 0.32,
                 "Customer": 0.24, "Safety": 0.14, "ESG|environmental": 0.10, "Discretion": 0.22,
                 "Other": 0.05, "None|Not applicable": 0.0},
        "rest": 0.1, "none_pattern": "None|Not applicable",
        "anchor": "bonus_measures_dep",
        "drivers": "Conditional on bonus existing (REW_INC_103); company financial + individual blend is the dominant design",
        "rationale": "Mainstream bonus design blends company financials with individual performance; sales/customer measures sector-dependent.",
        "source": "well-understood market practice",
    },
    "REW_PAY_023": {
        "opts": {"Affordability|budget": 0.86, "Inflation|cost of living": 0.74,
                 "National Living Wage": 0.30, "Company performance": 0.62,
                 "Market competitiveness|Market": 0.58, "Union|collective": 0.18,
                 "Retention|turnover": 0.40, "Other": 0.05},
        "rest": 0.1,
        "anchor": "paybudget_profile",
        "drivers": "High Workforce_Frontline_% -> NLW pressure; Workforce_Unionised_% -> union factor",
        "rationale": "Affordability and inflation lead every published pay-planning survey; NLW pressure is specific to low-pay/frontline employers.",
        "source": "CIPD pay-planning-style norm",
    },
    "PROP_c177397f": {
        "opts": {"Right-to-work": 0.99, "references": 0.88, "Qualification": 0.30,
                 "Criminal record": 0.42, "Credit|financial": 0.10, "Social media": 0.08,
                 "Other": 0.05},
        "rest": 0.08,
        "anchor": "checks_sector",
        "drivers": "Right-to-work statutory for all; criminal checks -> Healthcare/Education/Charity/Public; credit checks -> Financial Services",
        "rationale": "Right-to-work checks are a legal requirement; references near-universal; DBS and credit checks are sector-specific.",
        "source": "gov.uk statutory duty + market practice",
    },
    "WEL_BMAP_FIN_SALARY_SACRIFICE_001": {
        "opts": {"Cycle": 0.48, "Pension": 0.58, "Childcare Vouchers": 0.10, "Other": 0.05,
                 "None of the above": 0.0, "Don't know": 0.0},
        "rest": 0.05, "none_pattern": "None of the above",
        "anchor": "salsac_size",
        "drivers": "FTE_Band up -> pension salary sacrifice; childcare vouchers low (scheme closed to new entrants 2018)",
        "rationale": "Pension salary sacrifice and Cycle-to-Work are the mainstream schemes; childcare vouchers closed to new entrants in 2018.",
        "source": "gov.uk scheme status + market practice",
    },
}

# Level ladder used by by-level matrices (top -> bottom)
LEVELS = ["board_executive", "director", "head_of", "senior_manager",
          "manager", "supervisor_team_leader", "frontline_individual_contributor"]

# Matrix specs are implemented as functions in regenerate.py (MATRIX_GEN),
# but their driver-map entries live here so the audit record is in one place.
MATRIX_DRIVERS = {
    "323ffcf1-749b-43f3-bf34-1de6b8b1ca67": "Max bonus % by level — laddered Board>…>Frontline; scale by Ownership (PLC/PE high, Public/Charity none); conditional on REW_INC_103.",
    "REW_INC_111": "Target bonus % by level — ~55% of max bonus ladder, same conditions.",
    "REW_INC_133": "LTI eligibility by level — PLC/PE top levels only; None for Public/Charity/most founder-led.",
    "REW_INC_LTI_MAX_01": "Max LTI % by level — conditional on eligibility; Board-heavy ladder.",
    "REW_INC_LTI_VALUE_TYP_01": "Target LTI % — ~half of max.",
    "REW_BEN_112": "Typical employer pension % by level — from org latent pension value (Public Sector high), small exec uplift; consistent with PROP_36b990f9 band.",
    "REW_BEN_PENS_EMP_MAX_01": "Max employer pension % — typical + 1–4pp.",
    "REW_BEN_PENS_EE_MAX_01": "Max employee % — 6–15% laddered (estimate).",
    "3faf1f0c-f753-497f-a395-384bba38c5e3": "PMI premium — Single<Partner<Family realistic premium ladder; conditional on PMI offered.",
    "REW_BEN_139": "PMI eligibility by level — top-down threshold from REW_BEN_044 breadth.",
    "fa0f46f6-61e3-41d1-a2d1-3e57483bb1cf": "Car allowance £ by level — laddered Board~£8–14k -> Manager~£3–5k; conditional on car allowance offered.",
    "REW_PAY_109": "Status car eligibility — top-down threshold, conditional on car allowance.",
    "ATT_HIR_AGENCY_RATE_01": "Agency % by level — rises toward frontline; scaled by Workforce_Shift_/Frontline_%.",
    "ATT_HIR_CPH_01": "Cost-per-hire % of pay — falls toward frontline (senior search premium).",
    "ATT_HIR_REPLACE_COST_01": "Replacement cost % salary — laddered, senior high.",
    "ATT_OBO_REGRET_ATTR_01": "Regretted attrition % — scaled from registry Turnover_Band, lower at top levels.",
    "MET_cd8efe96": "Time to hire days — Board~90 -> Frontline~3 weeks ladder.",
    "GRO_CAR_042": "Internal fill % — mid-level bump, lower at entry and Board.",
    "GRO_LEA_LD_SPEND_01": "L&D spend % of pay — 0.5–3% range, F-scaled, slight senior uplift.",
    "GRO_POT_041": "Succession coverage — depth scales with F (Advanced cover to Manager; Basic Board-only or none).",
    "INC_Q308527": "Representation % — sector-realistic gender mix; ethnicity London-weighted; other rows population-plausible.",
    "b1785613-96ed-4a64-9fd7-762d0ac65f19": "Employee notice — 1–4wk frontline to 12wk+ Board ladder (categorical weeks).",
    "REW_Q524161": "Employer notice — mirrors employee notice, never below statutory.",
    "REW_Q528801": "Overtime multiplier by shift — 1x day to 1.5–2x bank holiday; shift orgs only.",
    "REW_Q534581": "Pay multipliers by time — 1.0x standard rising to 1.5–2x bank holiday.",
    "PROP_168eb098": "Span of control — banded; widest at supervisor/frontline, narrow at Board; frontline-heavy orgs wider.",
    "REW_PAY_020": "Allowance pensionability — mostly No (allowances typically non-pensionable), Yes commoner in public sector.",
    "a7ed418e-b057-4b70-ab58-31e897b7c1b6": "Allowance £ values — only for allowances the org offers (REW_PAY_016); realistic £ ranges per allowance type.",
    "REW_FAI_TRONC_GROUPS_e5639ac2": "Tronc participation by level — hospitality only, frontline/supervisor groups.",
}

NUMERIC_DRIVERS = {
    "PROP_db35137e": "Candidate experience score 55–90, F-tilted.",
    "PROP_8153af15": "Application-to-first-response 1–10 days, F-tilted down.",
    "PROP_b799860a": "Offer acceptance 75–96%, brand/F-tilted.",
    "PROP_e91c054c": "Referral share 5–30%.",
    "PROP_94199ca7": "Contingent workforce 2–25%, shift/frontline-tilted.",
    "PROP_3cb02f77": "Revenue per FTE — sector-scaled lognormal (estimate).",
    "PROP_d4b98d24": "Operating profit per FTE — margin on revenue/FTE; low for charity/public (estimate).",
    "PROP_e63cf45a": "Workforce cost % revenue — sector-typical bands (estimate).",
    "PROP_d16bae79": "Workforce cost per FTE £30–70k, sector-tilted.",
    "PROP_9620d380": "HR cost per employee £500–1,800, size-down.",
    "PROP_8d9d9ac5": "HR cost 1–4% of workforce cost.",
    "PROP_acdc8dd9": "HR tech spend £40–350 per employee, systems-maturity-tilted.",
    "PROP_3315e16b": "Learning hours 8–45/yr, F-tilted.",
    "PROP_9e3b1d18": "Early attrition % — registry Turnover_Band × ~1.3 with noise.",
    "PROP_02c9eb9e": "Engagement score 55–85, Employee_Voice/Advocacy-tilted.",
    "PROP_30ae24e7": "eNPS 0–55 (floor 0 per library), advocacy-tilted.",
    "PROP_9e4ad87f": "Salary increase budget 2.5–5.5%, Budget_Flexibility-tilted.",
}
